src/objects/ScheduledTSDetails__c.object
<CustomObject>
    <fields>
        <fullName>CurrentBatchProcessId__c</fullName>
        <label>CurrentBatchProcessId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentNodeIndex__c</fullName>
        <label>CurrentNodeIndex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DaysToShift__c</fullName>
        <label>DaysToShift</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DetailJson__c</fullName>
        <label>DetailJson</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Errors__c</fullName>
        <label>Errors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueProcessId__c</fullName>
        <label>QueueProcessId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Started_Date__c</fullName>
        <label>Started Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ScheduledTSDetails</label>
    <nameField>
        <label>ScheduledTSDetails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduledTSDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduledTimeShifting.cls
global class ScheduledTimeShifting implements Schedulable {

	private Integer daysToShift;
	private List<WaveTimeShiftingItem> timeShiftingItems;

	global ScheduledTimeShifting(){
		this.timeShiftingItems = new List<WaveTimeShiftingItem>();
	}

	global void execute(SchedulableContext sc) {
		this.calculateDaysToShift();
		this.selectMetadataAndBuildNodes();
		this.processTimeShiftingObjects(0);
	}

	private void calculateDaysToShift(){
		String soqlQuery = 'SELECT CloseDate FROM Opportunity WHERE External_Id__c LIKE \'W_Opportunity%\' AND StageName = \'Closed Won\'';
		
		soqlQuery += ' ORDER BY CloseDate DESC NULLS LAST';
		soqlQuery += ' LIMIT 1';

		List<sObject> sobjList = Database.query(soqlQuery);
		ScheduledTSDetails__c tsDetails = new ScheduledTSDetails__c();

		if(sobjList.size() > 0){				
			sObject s = sobjList.get(0);
			DateTime foundDate = (DateTime)s.get('CloseDate');
			
			this.daysToShift = foundDate.dateGMT().daysBetween(Date.today());
		}
		else{
			this.daysToShift = 0;
		}
	}

	private void selectMetadataAndBuildNodes(){
		HttpRequest req = new HttpRequest();
		req.setEndpoint('https://s3-us-west-2.amazonaws.com/ac-sdo-repo/sales/WaveForSales.json');
        req.setMethod('GET');
		Http http = new Http();
        HTTPResponse res = http.send(req);

        String jsonMetadata = res.getBody();
		WaveMetadataApplication selectedAppMetadata = (WaveMetadataApplication)JSON.deserialize(jsonMetadata, WaveMetadataApplication.class);
	
		for(WaveMetadataApplicationObject wmaObj: selectedAppMetadata.objects) {
			if(wmaObj.dateFieldsToShift != null && wmaObj.dateFieldsToShift.size() > 0){
				WaveTimeShiftingItem timeShiftingItem = new WaveTimeShiftingItem();
				timeShiftingItem.appType = selectedAppMetadata.appType;
				timeShiftingItem.objectTypeName = wmaObj.Name;
				timeShiftingItem.fieldsToTimeShift = wmaObj.dateFieldsToShift;
				this.timeShiftingItems.add(timeShiftingItem);
			}
		}
	}

	private void processTimeShiftingObjects(Integer currentNodeIndex){
		if(this.timeShiftingItems.size() > 0){
			ScheduledTSDetails__c tsDetails = new ScheduledTSDetails__c();
			WaveTimeShiftingItem currentNode = this.timeShiftingItems.get(currentNodeIndex);

			// Start the batch and queue process
			TimeShiftingBatch batchProcess = new TimeShiftingBatch(currentNode.objectTypeName, currentNode.fieldsToTimeShift, this.daysToShift);
			CheckTimeShiftingQueue tsQueue = new CheckTimeShiftingQueue();

			String tsDetailsJson = JSON.serialize(this.timeShiftingItems);

			tsDetails.DetailJson__c = tsDetailsJson;
			tsDetails.DaysToShift__c = this.daysToShift;
			tsDetails.Started_Date__c = Datetime.now();
			tsDetails.Status__c = 'In Progress';
			tsDetails.Errors__c = '';
			tsDetails.CurrentNodeIndex__c = 0;
			tsDetails.CurrentBatchProcessId__c = Database.executeBatch(batchProcess, 800);
			tsDetails.QueueProcessId__c = System.enqueueJob(tsQueue);
			insert tsDetails;
		}
	}
}